[package]
name = "bruteforce"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
itertools = "0.12.1"
wf-mods.workspace = true
wf-score.workspace = true
wf-stats.workspace = true
