[package]
name = "wf-modifier-proc-macro"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.82"
quote = "1.0.36"
syn = { version = "2.0.64", features = ["full"] }
wf-stats.workspace = true
